apiVersion: v1
kind: Namespace
metadata:
  name: aws-application-networking-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-api-controller
  namespace: aws-application-networking-system
