name: Build and Deploy Apps

on:
  workflow_dispatch:
jobs:
  deploy-aws-resources:
    defaults:
      run:
        working-directory: terraform/apps
    name: Deploy AWS Resources
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Terraform apply
        id: terraform
        run: |
          terraform apply -auto-approve

  build:
    needs: deploy-aws-resources
    defaults:
      run:
        working-directory: apps
    name: Build and Push to ECR with Docker Buildx Cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [sample-pod-identity]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image with Buildx
        run: |
          docker buildx build \
            --tag "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ matrix.service }}:${{github.sha}}" \
            --push \
            -f "cmd/${{ matrix.service }}/Dockerfile" \
            .
