name: Execute Terraform

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command"
        required: true
        type: choice
        options:
          - "plan"
          - "apply -auto-approve"
          - "destroy -auto-approve"
        default: "plan"
env:
  WORKING_DIRECTORY: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{vars.AWS_ROLE_ARN}}
          role-session-name: GitHubActions

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="bucket=${{vars.TF_STATE_BUCKET}}"
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Terraform ${{ github.event.inputs.command }}
        id: terraform
        run: |
          terraform ${{ github.event.inputs.command }} \

        working-directory: ${{env.WORKING_DIRECTORY}}
